# Generated by Django 4.2.13 on 2024-05-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_post', '0002_alter_newspost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
