# Generated by Django 4.2.13 on 2024-05-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_post', '0003_alter_newspost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_post_image'),
        ),
    ]
